Hello {{recipient.name}}!

<@{{instigator.id}}> has promoted you to Raider and this obviously have some benefits besides having the same loot priority as everyone else.

Being a Raider means:

  - Free flasks, pots, and food for the guild raids for your main
  - Free guild repairs (1000g per day)
  - Free gems from the guild bank (cheap ones mostly)

The rules of the guild bank is such that, **if** you can take something, you're **allowed** to take it, in moderation obviously. and only for personal use (not for alts, just your main) - also the guild bank welcomes any and all contributions of whatever you don't need/want (mats, gold, flasks, pots, pets, whatever) but it is **not** mandatory to contribute and nobody really checks.

It also means that we like you and think you make a great addition to the guild! =D

Please note that this promotion does not _automatically_ take effect in-game - an Officer will promote you in-game as soon as possible.

This message was sent automatically on behalf of {{instigator.name}} because we're lazy and can't be arsed to write these messages manually. =P

If you have any questions, feel free to message {{instigator.name}} or any Officer.